[DEFAULT]
config_schema_input = dqx_config

[DEV]
server_hostname = dbc-4b58157d-c7bb.cloud.databricks.com
http_path = /sql/1.0/warehouses/d1ab6da38ff963c2
token = token
job_id = 737121623984611

[PROD]
server_hostname = adb-production-url.net
http_path = sql/protocolv1/o/prod/path
token = dapi_prod_token
job_id = 987654321